application: limukassa
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static_files

- url: /.*
  script: limukassa.py
  login: required

- url: /admin
  script: admin.py
  login: admin
