application: onko-voittoa
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static_files

- url: /
  script: onko-voittoa.py
  login: required
- url: /tulokset
  script: onko-voittoa.py
  login: admin
- url: /voitot
  script: onko-voittoa.py
  login: admin
- url: /asetukset
  script: onko-voittoa.py
  login: required

